// <auto-generated />
using EFIntroductionMVC.Doa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFIntroductionMVC.Migrations
{
    [DbContext(typeof(InviteeContext))]
    [Migration("20200831202929_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");
#pragma warning restore 612, 618
        }
    }
}
