// <auto-generated />
using EFIntroductionMVC.Doa;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFIntroductionMVC.Migrations
{
    [DbContext(typeof(InviteeContext))]
    [Migration("20200831204452_AddGetSet")]
    partial class AddGetSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("EFIntroductionMVC.Models.HousePartyInvitee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isAttending")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int>("numberOfPartiesAttended")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("invitees");
                });
#pragma warning restore 612, 618
        }
    }
}
